name: CI

on:
  workflow_dispatch: # allows manual triggering
    inputs:
      create_release:
        description: "Create new release"
        required: true
        type: boolean
#  push:
#    tags:
#      - release-*

jobs:
  build:
    strategy:
      matrix:
        version:
          #- PYVERSION: 3.12.10
          #  PYNAME: 3.12.10
          #  PYARCH: 64

          - PYVERSION: 3.13.5
            PYNAME: 3.13.5
            PYARCH: 64

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

#      - name: Define Env
#        shell: cmd
#        run: echo "%PYVERSION% - %PYNAME% - %PYARCH%"
#        env:
#          PYVERSION: ${{ matrix.version.PYVERSION }}
#          PYNAME: ${{ matrix.version.PYNAME }}
#          PYARCH: ${{ matrix.version.PYARCH }}

      - name: Run the build
        shell: powershell
        run: |
          echo "${env:PYVERSION} - ${env:PYNAME} - ${env:PYARCH}"
          .\download.ps1
          #7z a Python-${env:PYNAME}-${env:PYARCH}.zip Python-${env:PYNAME}-${env:PYARCH}
          dir
        env:
          PYVERSION: ${{ matrix.version.PYVERSION }}
          PYNAME: ${{ matrix.version.PYNAME }}
          PYARCH: ${{ matrix.version.PYARCH }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Python-${{ matrix.version.PYNAME }}-${{ matrix.version.PYARCH }}
          #path: Python-${{ matrix.version.PYNAME }}-${{ matrix.version.PYARCH }}.zip
          path: |
            ./Python-${{ matrix.version.PYNAME }}-${{ matrix.version.PYARCH }}/
            ./README.md
